url:
  Joymeet:
    test: https://test-api.joyhappier.com
    staging: https://staging-api.joyhappier.com
    prod: https://api.joyhappier.com
  Viva:
    test: https://test-api.vivaaaa.com
    staging: https://staging-api.vivaaaa.com
    prod: https://api.vivaaaa.com

Viva_headers:
  Z-Client-Id: '4886037297291990'
  Z-Lon: '0'
  Z-Lat: '0'
  Z-Language: 'en-us'
  Z-Timezone: 'GMT-06:00'
  Content-Type: 'application/json'
  Z_Auth_Token: 'E1ZHGWANYHCmMKxuxfiD9h+tgxHCSnnW+KglYtK/ZIxhiYuYcCsWU3yHlnTlTVhaZz8pebYZDs7uJjsMKVKXx8HgGEa6uMS2zmBchcOrdZr601JInImziL9oGZwa1yOE'

Joymeet_headers:
  Z-Client-Id: '4886037297291990'
  Z-Lon: '0'
  Z-Lat: '0'
  Z-Language: 'en-us'
  Z_Auth_Token: '11111'

