url:
  Joymeet:
    test: https://test-api.joyhappier.com
    staging: https://staging-api.joyhappier.com
    prod: https://api.joyhappier.com
  Viva:
    test: https://test-api.vivaaaa.com
    staging: https://staging-api.vivaaaa.com
    prod: https://api.vivaaaa.com

Viva_headers:
  Z-App-Info: 'bundle_id=com.swerlzenfigmaderlas.swerl;version=1.3.0;build=13'
  Z-Client-Id: '4886037297291990'
  Z-Lon: '0'
  Z-Lat: '0'
  Z-Language: 'en-us'
  Z-User-Agent: '{page_name}/1.2.0 iOS/18.6.2 (iPhone 14)'
  Z-Timezone: 'GMT-06:00'
  Content-Type: 'application/json'

Joymeet_headers:
  Z-App-Info: 'bundle_id=com.swerlzenfigmaderlas.swerl;version=1.3.0;build=13'
  Z-Client-Id: '4886037297291990'
  Z-Lon: '0'
  Z-Lat: '0'
  Z-Language: 'en-us'
  Z-User-Agent: '{page_name}/1.2.0 iOS/18.6.2 (iPhone 14)'